package aiworkspace

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

const defaultSystemPrompt = "You receive an anonymized prompt generated by klovys99. Preserve placeholder tokens exactly as they appear and answer the user's request using only the anonymized content you were given."

type Service struct {
	client    *http.Client
	providers map[string]providerDefinition
	oauth     *claudeOAuthManager
	store     *conversationStore
	creds     *credentialStore
}

type MetadataProvider interface {
	Metadata() []ProviderDescriptor
}

type CompletionProvider interface {
	Complete(ctx context.Context, request CompletionRequest) (CompletionResponse, error)
}

type ProviderDescriptor struct {
	ID                string             `json:"id"`
	Label             string             `json:"label"`
	Description       string             `json:"description"`
	Available         bool               `json:"available"`
	UnavailableReason string             `json:"unavailable_reason,omitempty"`
	DefaultMethod     string             `json:"default_method,omitempty"`
	DefaultModel      string             `json:"default_model,omitempty"`
	Methods           []MethodDescriptor `json:"methods"`
	Models            []string           `json:"models"`
}

type MethodDescriptor struct {
	ID                string        `json:"id"`
	Label             string        `json:"label"`
	Available         bool          `json:"available"`
	UnavailableReason string        `json:"unavailable_reason,omitempty"`
	Fields            []FieldSchema `json:"fields"`
}

type FieldSchema struct {
	Key         string `json:"key"`
	Label       string `json:"label"`
	InputType   string `json:"input_type"`
	Required    bool   `json:"required"`
	Secret      bool   `json:"secret,omitempty"`
	Multiline   bool   `json:"multiline,omitempty"`
	Placeholder string `json:"placeholder,omitempty"`
}

type CompletionRequest struct {
	ConversationID   string            `json:"conversation_id"`
	Provider         string            `json:"provider"`
	Method           string            `json:"method"`
	Model            string            `json:"model"`
	AnonymizedPrompt string            `json:"anonymized_prompt"`
	SystemPrompt     string            `json:"system_prompt"`
	Config           map[string]string `json:"config"`
}

type SaveCredentialsRequest struct {
	Method string            `json:"method"`
	Config map[string]string `json:"config"`
}

type CompletionResponse struct {
	ConversationID   string `json:"conversation_id"`
	Provider         string `json:"provider"`
	Method           string `json:"method"`
	Model            string `json:"model"`
	AnonymizedPrompt string `json:"anonymized_prompt"`
	ResponseText     string `json:"response_text"`
}

type providerDefinition struct {
	descriptor ProviderDescriptor
	methods    map[string]providerMethod
}

type providerMethod struct {
	descriptor MethodDescriptor
	call       providerCall
}

type providerCall func(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (string, error)

type serviceContextKey struct{}

type apiError struct {
	StatusCode int
	Message    string
}

func (e *apiError) Error() string {
	return e.Message
}

func (e *apiError) GetStatusCode() int {
	return e.StatusCode
}

func NewService() *Service {
	service := &Service{
		client: &http.Client{Timeout: 90 * time.Second},
		oauth:  newClaudeOAuthManager(defaultWorkspaceStateDir(), &liveClaudeRunner{}),
		store:  newConversationStore(defaultWorkspaceStateDir()),
		creds:  newCredentialStore(defaultWorkspaceStateDir()),
	}
	service.providers = map[string]providerDefinition{
		"claude": {
			descriptor: ProviderDescriptor{
				ID:            "claude",
				Label:         "Claude",
				Description:   "Anthropic direct API key.",
				Available:     true,
				DefaultMethod: "api_key",
				DefaultModel:  "claude-sonnet-4-6",
				Methods: []MethodDescriptor{
					{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Anthropic API key", InputType: "password", Required: true, Secret: true, Placeholder: "sk-ant-..."},
						},
					},
				},
				Models: []string{"claude-opus-4-8", "claude-sonnet-4-6", "claude-haiku-4-5-20251001"},
			},
			methods: map[string]providerMethod{
				"api_key": {
					descriptor: MethodDescriptor{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Anthropic API key", InputType: "password", Required: true, Secret: true, Placeholder: "sk-ant-..."},
						},
					},
					call: callClaude,
				},
			},
		},
		"gemini": {
			descriptor: ProviderDescriptor{
				ID:            "gemini",
				Label:         "Gemini",
				Description:   "Google Gemini API via API key.",
				Available:     true,
				DefaultMethod: "api_key",
				DefaultModel:  "gemini-2.5-flash",
				Methods: []MethodDescriptor{
					{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Gemini API key", InputType: "password", Required: true, Secret: true, Placeholder: "AIza..."},
						},
					},
				},
				Models: []string{"gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.5-pro"},
			},
			methods: map[string]providerMethod{
				"api_key": {
					descriptor: MethodDescriptor{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Gemini API key", InputType: "password", Required: true, Secret: true, Placeholder: "AIza..."},
						},
					},
					call: callGemini,
				},
			},
		},
		"openai": {
			descriptor: ProviderDescriptor{
				ID:            "openai",
				Label:         "OpenAI",
				Description:   "OpenAI Chat Completions with a direct API key.",
				Available:     true,
				DefaultMethod: "api_key",
				DefaultModel:  "gpt-5.1-mini",
				Methods: []MethodDescriptor{
					{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "OpenAI API key", InputType: "password", Required: true, Secret: true, Placeholder: "sk-..."},
						},
					},
				},
				Models: []string{"gpt-5.1", "gpt-5.1-mini"},
			},
			methods: map[string]providerMethod{
				"api_key": {
					descriptor: MethodDescriptor{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "OpenAI API key", InputType: "password", Required: true, Secret: true, Placeholder: "sk-..."},
						},
					},
					call: callOpenAI,
				},
			},
		},
		"mistral": {
			descriptor: ProviderDescriptor{
				ID:            "mistral",
				Label:         "Mistral",
				Description:   "Mistral chat completions with API key auth.",
				Available:     true,
				DefaultMethod: "api_key",
				DefaultModel:  "mistral-small-3.2",
				Methods: []MethodDescriptor{
					{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Mistral API key", InputType: "password", Required: true, Secret: true, Placeholder: "..."},
						},
					},
				},
				Models: []string{"mistral-large-3", "mistral-small-3.2"},
			},
			methods: map[string]providerMethod{
				"api_key": {
					descriptor: MethodDescriptor{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Mistral API key", InputType: "password", Required: true, Secret: true, Placeholder: "..."},
						},
					},
					call: callMistral,
				},
			},
		},
	}
	return service
}

func (s *Service) Metadata() []ProviderDescriptor {
	if s == nil {
		return nil
	}
	providers := make([]ProviderDescriptor, 0, len(s.providers))
	order := []string{"claude", "gemini", "openai", "mistral"}
	for _, id := range order {
		provider, ok := s.providers[id]
		if !ok {
			continue
		}
		providers = append(providers, s.resolveProviderDescriptor(provider))
	}
	return providers
}

func (s *Service) resolveProviderDescriptor(provider providerDefinition) ProviderDescriptor {
	descriptor := provider.descriptor
	descriptor.Methods = append([]MethodDescriptor(nil), provider.descriptor.Methods...)
	hasConfiguredMethod := false
	for index, method := range descriptor.Methods {
		resolvedMethod := method
		if method.ID == "api_key" {
			if s.creds != nil && s.creds.Exists(descriptor.ID, method.ID) {
				resolvedMethod.Available = true
				resolvedMethod.UnavailableReason = ""
				hasConfiguredMethod = true
			} else {
				resolvedMethod.Available = false
				resolvedMethod.UnavailableReason = "Configure and save an API key in Compte IA"
			}
		}
		descriptor.Methods[index] = resolvedMethod
	}
	descriptor.Available = hasConfiguredMethod
	if !descriptor.Available {
		descriptor.UnavailableReason = "Configure and save an API key in Compte IA"
	} else {
		descriptor.UnavailableReason = ""
	}
	return descriptor
}

func (s *Service) SaveCredentials(providerID string, request SaveCredentialsRequest) (ProviderDescriptor, error) {
	if s == nil || s.creds == nil {
		return ProviderDescriptor{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	providerID = strings.TrimSpace(providerID)
	provider, ok := s.providers[providerID]
	if !ok {
		return ProviderDescriptor{}, &apiError{StatusCode: http.StatusBadRequest, Message: "Unsupported provider"}
	}
	methodID := strings.TrimSpace(request.Method)
	if methodID == "" {
		methodID = provider.descriptor.DefaultMethod
	}
	method, ok := provider.methods[methodID]
	if !ok {
		return ProviderDescriptor{}, &apiError{StatusCode: http.StatusBadRequest, Message: "Unsupported provider method"}
	}
	config := request.Config
	if config == nil {
		config = map[string]string{}
	}
	for _, field := range method.descriptor.Fields {
		if field.Required && strings.TrimSpace(config[field.Key]) == "" {
			return ProviderDescriptor{}, &apiError{StatusCode: http.StatusBadRequest, Message: fmt.Sprintf("Missing required provider field: %s", field.Key)}
		}
	}
	toPersist := map[string]string{}
	for _, field := range method.descriptor.Fields {
		if value := strings.TrimSpace(config[field.Key]); value != "" {
			toPersist[field.Key] = value
		}
	}
	if err := s.creds.Save(providerID, methodID, toPersist); err != nil {
		return ProviderDescriptor{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("save provider config: %v", err)}
	}
	return s.resolveProviderDescriptor(provider), nil
}

func (s *Service) ListConversations() ([]ConversationSummary, error) {
	if s == nil || s.store == nil {
		return nil, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	conversations, err := s.store.List()
	if err != nil {
		return nil, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("load conversations: %v", err)}
	}
	return conversations, nil
}

func (s *Service) CreateConversation() (ConversationDetail, error) {
	if s == nil || s.store == nil {
		return ConversationDetail{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	conversation, err := s.store.Create()
	if err != nil {
		return ConversationDetail{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("create conversation: %v", err)}
	}
	return conversation, nil
}

func (s *Service) GetConversation(id string) (ConversationDetail, error) {
	if s == nil || s.store == nil {
		return ConversationDetail{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	conversation, err := s.store.Get(strings.TrimSpace(id))
	if err != nil {
		if os.IsNotExist(err) {
			return ConversationDetail{}, &apiError{StatusCode: http.StatusNotFound, Message: "Conversation not found"}
		}
		return ConversationDetail{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("load conversation: %v", err)}
	}
	return conversation, nil
}

func (s *Service) Complete(ctx context.Context, request CompletionRequest) (CompletionResponse, error) {
	if s == nil {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	provider, ok := s.providers[strings.TrimSpace(request.Provider)]
	if !ok {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: "Unsupported provider"}
	}
	if !provider.descriptor.Available {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: provider.descriptor.UnavailableReason}
	}

	methodID := strings.TrimSpace(request.Method)
	if methodID == "" {
		methodID = provider.descriptor.DefaultMethod
	}
	method, ok := provider.methods[methodID]
	if !ok || !method.descriptor.Available {
		message := "Unsupported provider method"
		if ok && method.descriptor.UnavailableReason != "" {
			message = method.descriptor.UnavailableReason
		}
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: message}
	}

	prompt := strings.TrimSpace(request.AnonymizedPrompt)
	if prompt == "" {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: "An anonymized prompt is required"}
	}
	model := strings.TrimSpace(request.Model)
	if model == "" {
		model = provider.descriptor.DefaultModel
	}
	config := request.Config
	if config == nil {
		config = map[string]string{}
	}
	mergedConfig := map[string]string{}
	for key, value := range config {
		mergedConfig[key] = value
	}
	if s.creds != nil {
		storedConfig, err := s.creds.Load(provider.descriptor.ID, methodID)
		if err != nil {
			return CompletionResponse{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("load stored provider config: %v", err)}
		}
		for key, value := range storedConfig {
			if strings.TrimSpace(mergedConfig[key]) == "" {
				mergedConfig[key] = value
			}
		}
	}
	for _, field := range method.descriptor.Fields {
		if field.Required && strings.TrimSpace(mergedConfig[field.Key]) == "" {
			return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: fmt.Sprintf("Missing required provider field: %s", field.Key)}
		}
	}
	systemPrompt := strings.TrimSpace(request.SystemPrompt)
	if systemPrompt == "" {
		systemPrompt = defaultSystemPrompt
	}

	var (
		conversation ConversationDetail
		err          error
	)
	if conversationID := strings.TrimSpace(request.ConversationID); conversationID != "" {
		conversation, err = s.GetConversation(conversationID)
		if err != nil {
			return CompletionResponse{}, err
		}
	} else {
		conversation, err = s.CreateConversation()
		if err != nil {
			return CompletionResponse{}, err
		}
	}
	userMessage := ConversationMessage{
		Role:      "user",
		Content:   prompt,
		CreatedAt: time.Now().UTC(),
	}
	transcript := append(append([]ConversationMessage{}, conversation.Messages...), userMessage)
	responseText, err := method.call(context.WithValue(ctx, serviceContextKey{}, s), s.client, model, systemPrompt, providerWindow(transcript), mergedConfig)
	if err != nil {
		return CompletionResponse{}, err
	}
	if s.creds != nil {
		secretsToPersist := map[string]string{}
		for _, field := range method.descriptor.Fields {
			if !field.Secret {
				continue
			}
			if value := strings.TrimSpace(config[field.Key]); value != "" {
				secretsToPersist[field.Key] = value
			} else if value := strings.TrimSpace(mergedConfig[field.Key]); value != "" {
				secretsToPersist[field.Key] = value
			}
		}
		if len(secretsToPersist) > 0 {
			if err := s.creds.Save(provider.descriptor.ID, methodID, secretsToPersist); err != nil {
				return CompletionResponse{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("save provider config: %v", err)}
			}
		}
	}
	assistantMessage := ConversationMessage{
		Role:      "assistant",
		Content:   responseText,
		CreatedAt: time.Now().UTC(),
	}
	if strings.TrimSpace(conversation.Title) == "" {
		conversation.Title = truncateConversationTitle(prompt)
	}
	conversation.Provider = provider.descriptor.ID
	conversation.Method = methodID
	conversation.Model = model
	conversation.Messages = append(transcript, assistantMessage)
	if conversation.CreatedAt.IsZero() {
		conversation.CreatedAt = userMessage.CreatedAt
	}
	conversation.UpdatedAt = assistantMessage.CreatedAt
	if err := s.store.Save(conversation); err != nil {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("save conversation: %v", err)}
	}
	return CompletionResponse{
		ConversationID:   conversation.ID,
		Provider:         provider.descriptor.ID,
		Method:           methodID,
		Model:            model,
		AnonymizedPrompt: prompt,
		ResponseText:     responseText,
	}, nil
}

func (s *Service) ClaudeOAuthStatus() ClaudeOAuthStatusResponse {
	if s == nil || s.oauth == nil {
		return ClaudeOAuthStatusResponse{Method: "oauth_token"}
	}
	return s.oauth.status()
}

func (s *Service) StartClaudeOAuth(_ context.Context) (ClaudeOAuthStartResponse, error) {
	if s == nil || s.oauth == nil {
		return ClaudeOAuthStartResponse{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "Claude OAuth is unavailable"}
	}
	return s.oauth.start()
}

func (s *Service) SubmitClaudeOAuth(ctx context.Context, request ClaudeOAuthSubmitRequest) (ClaudeOAuthStatusResponse, error) {
	if s == nil || s.oauth == nil {
		return ClaudeOAuthStatusResponse{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "Claude OAuth is unavailable"}
	}
	return s.oauth.submit(ctx, request)
}

func (s *Service) CancelClaudeOAuth() error {
	if s == nil || s.oauth == nil {
		return nil
	}
	return s.oauth.cancel()
}

func (s *Service) UnlinkClaudeOAuth() error {
	if s == nil || s.oauth == nil {
		return nil
	}
	return s.oauth.unlink()
}

func callClaude(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (string, error) {
	payloadMessages := make([]map[string]any, 0, len(messages))
	for _, message := range messages {
		payloadMessages = append(payloadMessages, map[string]any{
			"role":    message.Role,
			"content": message.Content,
		})
	}
	payload := map[string]any{
		"model":      model,
		"max_tokens": 4096,
		"system":     systemPrompt,
		"messages":   payloadMessages,
	}
	headers := map[string]string{
		"x-api-key":         config["api_key"],
		"anthropic-version": "2023-06-01",
	}
	var response struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := doJSON(ctx, client, http.MethodPost, "https://api.anthropic.com/v1/messages", headers, payload, &response); err != nil {
		return "", wrapProviderError("Claude", err)
	}
	var builder strings.Builder
	for _, block := range response.Content {
		if block.Type == "text" {
			builder.WriteString(block.Text)
		}
	}
	return builder.String(), nil
}

func callClaudeOAuth(ctx context.Context, _ *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (string, error) {
	service, _ := ctx.Value(serviceContextKey{}).(*Service)
	if service == nil || service.oauth == nil {
		return "", &apiError{StatusCode: http.StatusServiceUnavailable, Message: "Claude OAuth is unavailable"}
	}
	token, err := service.oauth.loadToken()
	if err != nil {
		return "", err
	}
	prompt := ""
	if len(messages) > 0 {
		prompt = messages[len(messages)-1].Content
	}
	responseText, err := service.oauth.runner.RunOAuthPrompt(ctx, service.oauth.configDir(), token, model, systemPrompt, prompt)
	if err != nil {
		return "", normalizeCLIError("Claude request failed", err)
	}
	return responseText, nil
}

func callGemini(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (string, error) {
	endpoint := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s", url.PathEscape(model), url.QueryEscape(config["api_key"]))
	contents := make([]map[string]any, 0, len(messages))
	for _, message := range messages {
		role := message.Role
		if role == "assistant" {
			role = "model"
		}
		contents = append(contents, map[string]any{
			"role": role,
			"parts": []map[string]any{
				{"text": message.Content},
			},
		})
	}
	payload := map[string]any{
		"system_instruction": map[string]any{
			"parts": map[string]any{
				"text": systemPrompt,
			},
		},
		"contents": contents,
	}
	var response struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := doJSON(ctx, client, http.MethodPost, endpoint, nil, payload, &response); err != nil {
		return "", wrapProviderError("Gemini", err)
	}
	if len(response.Candidates) == 0 {
		return "", &apiError{StatusCode: http.StatusBadGateway, Message: "Gemini returned no candidate"}
	}
	var builder strings.Builder
	for _, part := range response.Candidates[0].Content.Parts {
		builder.WriteString(part.Text)
	}
	return builder.String(), nil
}

func callOpenAI(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (string, error) {
	payloadMessages := []map[string]string{
		{"role": "system", "content": systemPrompt},
	}
	for _, message := range messages {
		payloadMessages = append(payloadMessages, map[string]string{
			"role":    message.Role,
			"content": message.Content,
		})
	}
	payload := map[string]any{
		"model":    model,
		"messages": payloadMessages,
	}
	headers := map[string]string{
		"Authorization": "Bearer " + config["api_key"],
	}
	var response struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := doJSON(ctx, client, http.MethodPost, "https://api.openai.com/v1/chat/completions", headers, payload, &response); err != nil {
		return "", wrapProviderError("OpenAI", err)
	}
	if len(response.Choices) == 0 {
		return "", &apiError{StatusCode: http.StatusBadGateway, Message: "OpenAI returned no choice"}
	}
	return response.Choices[0].Message.Content, nil
}

func callMistral(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (string, error) {
	payloadMessages := []map[string]string{
		{"role": "system", "content": systemPrompt},
	}
	for _, message := range messages {
		payloadMessages = append(payloadMessages, map[string]string{
			"role":    message.Role,
			"content": message.Content,
		})
	}
	payload := map[string]any{
		"model":    model,
		"messages": payloadMessages,
	}
	headers := map[string]string{
		"Authorization": "Bearer " + config["api_key"],
	}
	var response struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := doJSON(ctx, client, http.MethodPost, "https://api.mistral.ai/v1/chat/completions", headers, payload, &response); err != nil {
		return "", wrapProviderError("Mistral", err)
	}
	if len(response.Choices) == 0 {
		return "", &apiError{StatusCode: http.StatusBadGateway, Message: "Mistral returned no choice"}
	}
	return response.Choices[0].Message.Content, nil
}

func doJSON(ctx context.Context, client *http.Client, method string, endpoint string, headers map[string]string, payload any, target any) error {
	body, err := json.Marshal(payload)
	if err != nil {
		return &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("encode request: %v", err)}
	}
	request, err := http.NewRequestWithContext(ctx, method, endpoint, bytes.NewReader(body))
	if err != nil {
		return &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("build request: %v", err)}
	}
	request.Header.Set("Content-Type", "application/json")
	for key, value := range headers {
		if strings.TrimSpace(value) != "" {
			request.Header.Set(key, value)
		}
	}
	response, err := client.Do(request)
	if err != nil {
		return &apiError{StatusCode: http.StatusBadGateway, Message: err.Error()}
	}
	defer response.Body.Close()
	responseBody, err := io.ReadAll(io.LimitReader(response.Body, 1<<20))
	if err != nil {
		return &apiError{StatusCode: http.StatusBadGateway, Message: fmt.Sprintf("read response: %v", err)}
	}
	if response.StatusCode >= http.StatusBadRequest {
		message := extractRemoteError(responseBody)
		if message == "" {
			message = strings.TrimSpace(string(responseBody))
		}
		if message == "" {
			message = response.Status
		}
		return &apiError{StatusCode: http.StatusBadGateway, Message: message}
	}
	if err := json.Unmarshal(responseBody, target); err != nil {
		return &apiError{StatusCode: http.StatusBadGateway, Message: fmt.Sprintf("decode response: %v", err)}
	}
	return nil
}

func extractRemoteError(body []byte) string {
	var payload struct {
		Error any `json:"error"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		return ""
	}
	switch value := payload.Error.(type) {
	case string:
		return value
	case map[string]any:
		if message, ok := value["message"].(string); ok {
			return message
		}
		if message, ok := value["status"].(string); ok {
			return message
		}
	}
	return ""
}

func wrapProviderError(provider string, err error) error {
	apiErr, ok := err.(*apiError)
	if !ok {
		return err
	}
	message := strings.TrimSpace(apiErr.Message)
	if message == "" {
		message = "request failed"
	}
	return &apiError{
		StatusCode: apiErr.StatusCode,
		Message:    fmt.Sprintf("%s request failed: %s", provider, message),
	}
}
