package aiworkspace

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/Korbicorp/klovys99/internal/anonymizer"
	"github.com/Korbicorp/klovys99/internal/credential"
	"github.com/Korbicorp/klovys99/internal/fileanonymizer"
	resty "gopkg.in/resty.v1"
)

const defaultSystemPrompt = "You receive an anonymized prompt generated by klovys99. Preserve placeholder tokens exactly as they appear and answer the user's request using only the anonymized content you were given."

type Service struct {
	client     *http.Client
	providers  map[string]providerDefinition
	oauth      *claudeOAuthManager
	store      *conversationStore
	creds      *credential.Store
	anonymizer conversationAnonymizer
	files      attachmentAnonymizer
	stateDir   string
}

type attachmentAnonymizer interface {
	Enabled() bool
	FailurePolicy() string
	MaxBytes() int64
	AnonymizeWithText(context.Context, string, string, []byte) (fileanonymizer.Output, error)
}

type conversationAnonymizer interface {
	NewRun() *anonymizer.Run
}

type MetadataProvider interface {
	Metadata() []ProviderDescriptor
}

type CompletionProvider interface {
	Complete(ctx context.Context, request CompletionRequest) (CompletionResponse, error)
}

type ProviderDescriptor struct {
	ID                string             `json:"id"`
	Label             string             `json:"label"`
	Description       string             `json:"description"`
	Available         bool               `json:"available"`
	UnavailableReason string             `json:"unavailable_reason,omitempty"`
	DefaultMethod     string             `json:"default_method,omitempty"`
	DefaultModel      string             `json:"default_model,omitempty"`
	Methods           []MethodDescriptor `json:"methods"`
	Models            []string           `json:"models"`
}

type MethodDescriptor struct {
	ID                string        `json:"id"`
	Label             string        `json:"label"`
	Available         bool          `json:"available"`
	UnavailableReason string        `json:"unavailable_reason,omitempty"`
	Fields            []FieldSchema `json:"fields"`
}

type FieldSchema struct {
	Key         string `json:"key"`
	Label       string `json:"label"`
	InputType   string `json:"input_type"`
	Required    bool   `json:"required"`
	Secret      bool   `json:"secret,omitempty"`
	Multiline   bool   `json:"multiline,omitempty"`
	Placeholder string `json:"placeholder,omitempty"`
}

type CompletionRequest struct {
	ConversationID   string              `json:"conversation_id"`
	Provider         string              `json:"provider"`
	Method           string              `json:"method"`
	Model            string              `json:"model"`
	AnonymizedPrompt string              `json:"anonymized_prompt"`
	SystemPrompt     string              `json:"system_prompt"`
	Config           map[string]string   `json:"config"`
	Attachment       *UploadedAttachment `json:"-"`
}

type SaveCredentialsRequest struct {
	Method string            `json:"method"`
	Config map[string]string `json:"config"`
}

type CompletionResponse struct {
	ConversationID          string             `json:"conversation_id"`
	Provider                string             `json:"provider"`
	Method                  string             `json:"method"`
	Model                   string             `json:"model"`
	AnonymizedPrompt        string             `json:"anonymized_prompt"`
	ResponseText            string             `json:"response_text"`
	ResponsePIIReplacements []PIIReplacement   `json:"response_pii_replacements,omitempty"`
	Attachment              *MessageAttachment `json:"attachment,omitempty"`
	Warning                 string             `json:"warning,omitempty"`
}

type providerCallResult struct {
	ResponseText      string
	ProviderSessionID string
}

type providerDefinition struct {
	descriptor ProviderDescriptor
	methods    map[string]providerMethod
}

type providerMethod struct {
	descriptor MethodDescriptor
	call       providerCall
}

type providerCall func(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (providerCallResult, error)

type serviceContextKey struct{}
type conversationContextKey struct{}

type apiError struct {
	StatusCode int
	Message    string
}

var aiWorkspaceTokenPattern = regexp.MustCompile(`\[[A-Z_]+_[0-9]+\]`)

func (e *apiError) Error() string {
	return e.Message
}

func (e *apiError) GetStatusCode() int {
	return e.StatusCode
}

func NewService(sharedAnonymizer ...conversationAnonymizer) *Service {
	var injected conversationAnonymizer
	if len(sharedAnonymizer) > 0 {
		injected = sharedAnonymizer[0]
	}
	return newService(injected, nil)
}

func NewServiceWithFiles(shared conversationAnonymizer, files attachmentAnonymizer) *Service {
	return newService(shared, files)
}

func (s *Service) MaxAttachmentBytes() int64 {
	if s == nil || s.files == nil {
		return fileanonymizer.DefaultMaxFileBytes
	}
	return s.files.MaxBytes()
}

func newService(injected conversationAnonymizer, files attachmentAnonymizer) *Service {
	stateDir := defaultWorkspaceStateDir()
	credentialStore := credential.NewStore(defaultWorkspaceStateDir())
	service := &Service{
		client:     &http.Client{Timeout: 90 * time.Second},
		oauth:      newClaudeOAuthManager(defaultWorkspaceStateDir(), credentialStore, nil),
		store:      newConversationStore(defaultWorkspaceStateDir()),
		creds:      credentialStore,
		anonymizer: injected,
		files:      files,
		stateDir:   stateDir,
	}
	service.providers = map[string]providerDefinition{
		"claude": {
			descriptor: ProviderDescriptor{
				ID:            "claude",
				Label:         "Claude",
				Description:   "Anthropic direct API key or Claude CLI OAuth token.",
				Available:     true,
				DefaultMethod: "api_key",
				DefaultModel:  "claude-sonnet-4-6",
				Methods: []MethodDescriptor{
					{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Anthropic API key", InputType: "password", Required: true, Secret: true, Placeholder: "sk-ant-..."},
						},
					},
					{
						ID:        "oauth_token",
						Label:     "Claude OAuth",
						Available: false,
					},
				},
				Models: []string{"claude-opus-4-8", "claude-sonnet-4-6", "claude-haiku-4-5-20251001"},
			},
			methods: map[string]providerMethod{
				"api_key": {
					descriptor: MethodDescriptor{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Anthropic API key", InputType: "password", Required: true, Secret: true, Placeholder: "sk-ant-..."},
						},
					},
					call: callClaude,
				},
				"oauth_token": {
					descriptor: MethodDescriptor{
						ID:        "oauth_token",
						Label:     "Claude OAuth",
						Available: false,
					},
					call: callClaudeOAuth,
				},
			},
		},
		"gemini": {
			descriptor: ProviderDescriptor{
				ID:            "gemini",
				Label:         "Gemini",
				Description:   "Google Gemini API via API key.",
				Available:     true,
				DefaultMethod: "api_key",
				DefaultModel:  "gemini-2.5-flash",
				Methods: []MethodDescriptor{
					{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Gemini API key", InputType: "password", Required: true, Secret: true, Placeholder: "AIza..."},
						},
					},
				},
				Models: []string{"gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.5-pro"},
			},
			methods: map[string]providerMethod{
				"api_key": {
					descriptor: MethodDescriptor{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Gemini API key", InputType: "password", Required: true, Secret: true, Placeholder: "AIza..."},
						},
					},
					call: callGemini,
				},
			},
		},
		"openai": {
			descriptor: ProviderDescriptor{
				ID:            "openai",
				Label:         "OpenAI",
				Description:   "OpenAI Chat Completions with a direct API key.",
				Available:     true,
				DefaultMethod: "api_key",
				DefaultModel:  "gpt-5.1-mini",
				Methods: []MethodDescriptor{
					{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "OpenAI API key", InputType: "password", Required: true, Secret: true, Placeholder: "sk-..."},
						},
					},
				},
				Models: []string{"gpt-5.1", "gpt-5.1-mini"},
			},
			methods: map[string]providerMethod{
				"api_key": {
					descriptor: MethodDescriptor{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "OpenAI API key", InputType: "password", Required: true, Secret: true, Placeholder: "sk-..."},
						},
					},
					call: callOpenAI,
				},
			},
		},
		"mistral": {
			descriptor: ProviderDescriptor{
				ID:            "mistral",
				Label:         "Mistral",
				Description:   "Mistral chat completions with API key auth.",
				Available:     true,
				DefaultMethod: "api_key",
				DefaultModel:  "mistral-small-3.2",
				Methods: []MethodDescriptor{
					{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Mistral API key", InputType: "password", Required: true, Secret: true, Placeholder: "..."},
						},
					},
				},
				Models: []string{"mistral-large-3", "mistral-small-3.2"},
			},
			methods: map[string]providerMethod{
				"api_key": {
					descriptor: MethodDescriptor{
						ID:        "api_key",
						Label:     "API key",
						Available: true,
						Fields: []FieldSchema{
							{Key: "api_key", Label: "Mistral API key", InputType: "password", Required: true, Secret: true, Placeholder: "..."},
						},
					},
					call: callMistral,
				},
			},
		},
	}
	return service
}

func (s *Service) Metadata() []ProviderDescriptor {
	if s == nil {
		return nil
	}
	providers := make([]ProviderDescriptor, 0, len(s.providers))
	order := []string{"claude", "gemini", "openai", "mistral"}
	for _, id := range order {
		provider, ok := s.providers[id]
		if !ok {
			continue
		}
		providers = append(providers, s.resolveProviderDescriptor(provider))
	}
	return providers
}

func (s *Service) resolveProviderDescriptor(provider providerDefinition) ProviderDescriptor {
	descriptor := provider.descriptor
	descriptor.Methods = append([]MethodDescriptor(nil), provider.descriptor.Methods...)
	hasConfiguredMethod := false
	oauthAvailable, oauthUnavailableReason := false, ""
	oauthLinked := false
	if descriptor.ID == "claude" && s.oauth != nil {
		oauthAvailable, oauthUnavailableReason = s.oauth.availability()
		oauthLinked = s.oauth.status().Linked
	}
	for index, method := range descriptor.Methods {
		resolvedMethod := method
		switch method.ID {
		case "api_key":
			if s.creds != nil && s.creds.ProviderExists(descriptor.ID, method.ID) {
				resolvedMethod.Available = true
				resolvedMethod.UnavailableReason = ""
				hasConfiguredMethod = true
			} else {
				resolvedMethod.Available = false
				resolvedMethod.UnavailableReason = "Configure and save an API key in Compte IA"
			}
		case "oauth_token":
			resolvedMethod.Available = oauthLinked && oauthUnavailableReason == ""
			switch {
			case oauthUnavailableReason != "":
				resolvedMethod.UnavailableReason = oauthUnavailableReason
			case oauthLinked:
				resolvedMethod.UnavailableReason = ""
				hasConfiguredMethod = true
			case oauthAvailable:
				resolvedMethod.UnavailableReason = "Connect Claude OAuth in Compte IA"
			default:
				resolvedMethod.UnavailableReason = "Claude OAuth is unavailable"
			}
		}
		descriptor.Methods[index] = resolvedMethod
	}
	descriptor.Available = hasConfiguredMethod
	if descriptor.Available {
		descriptor.UnavailableReason = ""
		if oauthLinked && oauthUnavailableReason == "" {
			descriptor.DefaultMethod = "oauth_token"
		} else {
			descriptor.DefaultMethod = "api_key"
		}
		return descriptor
	}
	if descriptor.ID == "claude" && oauthUnavailableReason != "" {
		descriptor.UnavailableReason = oauthUnavailableReason
	} else {
		descriptor.UnavailableReason = "Configure and save an API key in Compte IA"
	}
	return descriptor
}

func (s *Service) SaveCredentials(providerID string, request SaveCredentialsRequest) (ProviderDescriptor, error) {
	if s == nil || s.creds == nil {
		return ProviderDescriptor{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	providerID = strings.TrimSpace(providerID)
	provider, ok := s.providers[providerID]
	if !ok {
		return ProviderDescriptor{}, &apiError{StatusCode: http.StatusBadRequest, Message: "Unsupported provider"}
	}
	methodID := strings.TrimSpace(request.Method)
	if methodID == "" {
		methodID = provider.descriptor.DefaultMethod
	}
	method, ok := provider.methods[methodID]
	if !ok {
		return ProviderDescriptor{}, &apiError{StatusCode: http.StatusBadRequest, Message: "Unsupported provider method"}
	}
	config := request.Config
	if config == nil {
		config = map[string]string{}
	}
	for _, field := range method.descriptor.Fields {
		if field.Required && strings.TrimSpace(config[field.Key]) == "" {
			return ProviderDescriptor{}, &apiError{StatusCode: http.StatusBadRequest, Message: fmt.Sprintf("Missing required provider field: %s", field.Key)}
		}
	}
	toPersist := map[string]string{}
	for _, field := range method.descriptor.Fields {
		if value := strings.TrimSpace(config[field.Key]); value != "" {
			toPersist[field.Key] = value
		}
	}
	if err := s.creds.SaveProvider(providerID, methodID, toPersist); err != nil {
		return ProviderDescriptor{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("save provider config: %v", err)}
	}
	return s.resolveProviderDescriptor(provider), nil
}

func (s *Service) ListConversations() ([]ConversationSummary, error) {
	if s == nil || s.store == nil {
		return nil, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	conversations, err := s.store.List()
	if err != nil {
		return nil, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("load conversations: %v", err)}
	}
	for index := range conversations {
		conversations[index].Title = s.restoreText(conversations[index].Title)
	}
	return conversations, nil
}

func (s *Service) CreateConversation() (ConversationDetail, error) {
	if s == nil || s.store == nil {
		return ConversationDetail{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	conversation, err := s.store.Create()
	if err != nil {
		return ConversationDetail{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("create conversation: %v", err)}
	}
	return conversation, nil
}

func (s *Service) GetConversation(id string) (ConversationDetail, error) {
	return s.getConversation(id, true)
}

func (s *Service) getConversation(id string, restore bool) (ConversationDetail, error) {
	if s == nil || s.store == nil {
		return ConversationDetail{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	conversation, err := s.store.Get(strings.TrimSpace(id))
	if err != nil {
		if os.IsNotExist(err) {
			return ConversationDetail{}, &apiError{StatusCode: http.StatusNotFound, Message: "Conversation not found"}
		}
		return ConversationDetail{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("load conversation: %v", err)}
	}
	if restore {
		conversation = s.restoreConversation(conversation)
	}
	return conversation, nil
}

func (s *Service) Complete(ctx context.Context, request CompletionRequest) (CompletionResponse, error) {
	if s == nil {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "AI workspace is unavailable"}
	}
	provider, ok := s.providers[strings.TrimSpace(request.Provider)]
	if !ok {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: "Unsupported provider"}
	}
	resolvedProvider := s.resolveProviderDescriptor(provider)

	methodID := strings.TrimSpace(request.Method)
	if methodID == "" {
		methodID = resolvedProvider.DefaultMethod
	}
	method, ok := provider.methods[methodID]
	resolvedMethod := method.descriptor
	if candidate := findMethodDescriptor(resolvedProvider.Methods, methodID); candidate != nil {
		resolvedMethod = *candidate
	}
	if !ok {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: "Unsupported provider method"}
	}
	if methodID == "oauth_token" && !resolvedMethod.Available {
		message := "Unsupported provider method"
		if resolvedMethod.UnavailableReason != "" {
			message = resolvedMethod.UnavailableReason
		}
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: message}
	}

	prompt := strings.TrimSpace(request.AnonymizedPrompt)
	if prompt == "" && request.Attachment == nil {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: "An anonymized prompt is required"}
	}
	model := strings.TrimSpace(request.Model)
	if model == "" {
		model = provider.descriptor.DefaultModel
	}
	config := request.Config
	if config == nil {
		config = map[string]string{}
	}
	mergedConfig := map[string]string{}
	for key, value := range config {
		mergedConfig[key] = value
	}
	if s.creds != nil {
		storedConfig, err := s.creds.LoadProvider(provider.descriptor.ID, methodID)
		if err != nil {
			return CompletionResponse{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("load stored provider config: %v", err)}
		}
		for key, value := range storedConfig {
			if strings.TrimSpace(mergedConfig[key]) == "" {
				mergedConfig[key] = value
			}
		}
	}
	for _, field := range resolvedMethod.Fields {
		if field.Required && strings.TrimSpace(mergedConfig[field.Key]) == "" {
			return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: fmt.Sprintf("Missing required provider field: %s", field.Key)}
		}
	}
	systemPrompt := strings.TrimSpace(request.SystemPrompt)
	if systemPrompt == "" {
		systemPrompt = defaultSystemPrompt
	}

	var (
		conversation ConversationDetail
		err          error
	)
	if conversationID := strings.TrimSpace(request.ConversationID); conversationID != "" {
		conversation, err = s.getConversation(conversationID, false)
		if err != nil {
			return CompletionResponse{}, err
		}
	} else {
		conversation, err = s.CreateConversation()
		if err != nil {
			return CompletionResponse{}, err
		}
	}
	attachment, warning, err := s.prepareAttachment(ctx, provider.descriptor.ID, request.Attachment)
	if err != nil {
		return CompletionResponse{}, err
	}
	if prompt == "" && (attachment == nil || attachment.Status == attachmentStatusRemoved) {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusBadRequest, Message: "A prompt is required when the attachment is removed"}
	}
	userMessage := ConversationMessage{
		Role:       "user",
		Content:    prompt,
		CreatedAt:  time.Now().UTC(),
		Attachment: attachment,
	}
	transcript := append(append([]ConversationMessage{}, conversation.Messages...), userMessage)
	if err := s.loadTranscriptAttachments(transcript); err != nil {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("load attachment: %v", err)}
	}
	callCtx := context.WithValue(ctx, serviceContextKey{}, s)
	callCtx = context.WithValue(callCtx, conversationContextKey{}, conversation)
	callResult, err := method.call(callCtx, s.client, model, systemPrompt, providerWindow(transcript), mergedConfig)
	if err != nil {
		return CompletionResponse{}, err
	}
	if s.creds != nil {
		secretsToPersist := map[string]string{}
		for _, field := range resolvedMethod.Fields {
			if !field.Secret {
				continue
			}
			if value := strings.TrimSpace(config[field.Key]); value != "" {
				secretsToPersist[field.Key] = value
			} else if value := strings.TrimSpace(mergedConfig[field.Key]); value != "" {
				secretsToPersist[field.Key] = value
			}
		}
		if len(secretsToPersist) > 0 {
			if err := s.creds.SaveProvider(provider.descriptor.ID, methodID, secretsToPersist); err != nil {
				return CompletionResponse{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("save provider config: %v", err)}
			}
		}
	}
	assistantMessage := ConversationMessage{
		Role:      "assistant",
		Content:   callResult.ResponseText,
		CreatedAt: time.Now().UTC(),
	}
	if strings.TrimSpace(conversation.Title) == "" {
		title := prompt
		if title == "" && attachment != nil {
			title = attachment.Filename
		}
		conversation.Title = truncateConversationTitle(title)
	}
	conversation.Provider = provider.descriptor.ID
	conversation.Method = methodID
	conversation.Model = model
	conversation.ProviderSessionID = strings.TrimSpace(callResult.ProviderSessionID)
	conversation.Messages = append(transcript, assistantMessage)
	if err := s.saveAttachment(attachment); err != nil {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("save attachment: %v", err)}
	}
	for index := range conversation.Messages {
		if conversation.Messages[index].Attachment != nil {
			conversation.Messages[index].Attachment.Data = nil
		}
	}
	if conversation.CreatedAt.IsZero() {
		conversation.CreatedAt = userMessage.CreatedAt
	}
	conversation.UpdatedAt = assistantMessage.CreatedAt
	if err := s.store.Save(conversation); err != nil {
		return CompletionResponse{}, &apiError{StatusCode: http.StatusInternalServerError, Message: fmt.Sprintf("save conversation: %v", err)}
	}
	return CompletionResponse{
		ConversationID:          conversation.ID,
		Provider:                provider.descriptor.ID,
		Method:                  methodID,
		Model:                   model,
		AnonymizedPrompt:        prompt,
		ResponseText:            s.restoreText(callResult.ResponseText),
		ResponsePIIReplacements: s.buildPIIReplacements(callResult.ResponseText),
		Attachment:              attachment,
		Warning:                 warning,
	}, nil
}

func (s *Service) prepareAttachment(ctx context.Context, provider string, upload *UploadedAttachment) (*MessageAttachment, string, error) {
	if upload == nil {
		return nil, "", nil
	}
	attachment := &MessageAttachment{Filename: upload.Filename, MediaType: upload.MediaType, Size: int64(len(upload.Data))}
	if s.files == nil || !s.files.Enabled() {
		return nil, "", &apiError{StatusCode: http.StatusServiceUnavailable, Message: "File anonymization is unavailable"}
	}
	output, err := s.files.AnonymizeWithText(ctx, provider, upload.MediaType, upload.Data)
	if err == nil {
		attachment.Status = attachmentStatusAnonymized
		attachment.Reusable = true
		attachment.Data = output.Data
		attachment.Text = output.Text
		return attachment, "", nil
	}
	warning := fmt.Sprintf("File anonymization failed: %v", err)
	switch s.files.FailurePolicy() {
	case fileanonymizer.PolicyRemove:
		attachment.Status = attachmentStatusRemoved
		attachment.Warning = warning
		return attachment, warning, nil
	case fileanonymizer.PolicyPassthrough:
		attachment.Status = attachmentStatusPassthrough
		attachment.Data = upload.Data
		attachment.Warning = warning
		return attachment, warning, nil
	default:
		return nil, "", &apiError{StatusCode: http.StatusUnprocessableEntity, Message: warning}
	}
}

func (s *Service) loadTranscriptAttachments(messages []ConversationMessage) error {
	for index := range messages {
		if err := s.loadAttachmentData(messages[index].Attachment); err != nil {
			return err
		}
	}
	return nil
}

func (s *Service) restoreConversation(conversation ConversationDetail) ConversationDetail {
	conversation.Title = s.restoreText(conversation.Title)
	if len(conversation.Messages) == 0 {
		return conversation
	}
	messages := make([]ConversationMessage, len(conversation.Messages))
	for index, message := range conversation.Messages {
		messages[index] = message
		messages[index].PIIReplacements = s.buildPIIReplacements(message.Content)
		messages[index].Content = s.restoreText(message.Content)
	}
	conversation.Messages = messages
	return conversation
}

func (s *Service) restoreText(input string) string {
	if strings.TrimSpace(input) == "" || s == nil || s.anonymizer == nil {
		return input
	}
	run := s.anonymizer.NewRun()
	if run == nil {
		return input
	}
	defer func() {
		_ = run.Close()
	}()
	if restored, ok := run.Deanonymize(input); ok {
		return restored
	}
	return input
}

func (s *Service) buildPIIReplacements(input string) []PIIReplacement {
	if strings.TrimSpace(input) == "" || s == nil || s.anonymizer == nil {
		return nil
	}
	run := s.anonymizer.NewRun()
	if run == nil {
		return nil
	}
	defer func() {
		_ = run.Close()
	}()

	indices := aiWorkspaceTokenPattern.FindAllStringIndex(input, -1)
	if len(indices) == 0 {
		return nil
	}

	replacements := make([]PIIReplacement, 0, len(indices))
	outputLength := 0
	last := 0
	for _, index := range indices {
		outputLength += len(input[last:index[0]])
		token := input[index[0]:index[1]]
		value, ok := run.ValueForToken(token)
		if !ok {
			outputLength += len(token)
			last = index[1]
			continue
		}
		replacements = append(replacements, PIIReplacement{
			Type:  piiTypeFromToken(token),
			Token: token,
			Value: value,
			Start: outputLength,
			End:   outputLength + len(value),
		})
		outputLength += len(value)
		last = index[1]
	}
	if len(replacements) == 0 {
		return nil
	}
	return replacements
}

func piiTypeFromToken(token string) string {
	if len(token) < 4 || token[0] != '[' || token[len(token)-1] != ']' {
		return ""
	}
	trimmed := token[1 : len(token)-1]
	separator := strings.LastIndex(trimmed, "_")
	if separator <= 0 {
		return ""
	}
	return trimmed[:separator]
}

func findMethodDescriptor(methods []MethodDescriptor, methodID string) *MethodDescriptor {
	for index := range methods {
		if methods[index].ID == methodID {
			return &methods[index]
		}
	}
	return nil
}

func (s *Service) ClaudeOAuthStatus() ClaudeOAuthStatusResponse {
	if s == nil || s.oauth == nil {
		return ClaudeOAuthStatusResponse{Method: "oauth_token"}
	}
	return s.oauth.status()
}

func (s *Service) StartClaudeOAuth(_ context.Context) (ClaudeOAuthStartResponse, error) {
	if s == nil || s.oauth == nil {
		return ClaudeOAuthStartResponse{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "Claude OAuth is unavailable"}
	}
	return s.oauth.start()
}

func (s *Service) SubmitClaudeOAuth(ctx context.Context, request ClaudeOAuthSubmitRequest) (ClaudeOAuthStatusResponse, error) {
	if s == nil || s.oauth == nil {
		return ClaudeOAuthStatusResponse{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "Claude OAuth is unavailable"}
	}
	return s.oauth.submit(ctx, request)
}

func (s *Service) CancelClaudeOAuth() error {
	if s == nil || s.oauth == nil {
		return nil
	}
	return s.oauth.cancel()
}

func (s *Service) UnlinkClaudeOAuth() error {
	if s == nil || s.oauth == nil {
		return nil
	}
	return s.oauth.unlink()
}

func callClaude(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (providerCallResult, error) {
	payloadMessages := make([]map[string]any, 0, len(messages))
	for _, message := range messages {
		content := any(messageTextWithFallback(message))
		if attachment := message.Attachment; attachment != nil && len(attachment.Data) > 0 && supportsNativeDocument("claude", attachment.MediaType) {
			blocks := []map[string]any{}
			if strings.TrimSpace(message.Content) != "" {
				blocks = append(blocks, map[string]any{"type": "text", "text": message.Content})
			}
			blockType := "document"
			if strings.HasPrefix(strings.ToLower(attachment.MediaType), "image/") {
				blockType = "image"
			}
			blocks = append(blocks, map[string]any{"type": blockType, "source": map[string]any{"type": "base64", "media_type": attachment.MediaType, "data": base64.StdEncoding.EncodeToString(attachment.Data)}})
			content = blocks
		}
		payloadMessages = append(payloadMessages, map[string]any{
			"role":    message.Role,
			"content": content,
		})
	}
	payload := map[string]any{
		"model":      model,
		"max_tokens": 4096,
		"system":     systemPrompt,
		"messages":   payloadMessages,
	}
	headers := map[string]string{
		"x-api-key":         config["api_key"],
		"anthropic-version": "2023-06-01",
	}
	var response struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := doJSON(ctx, client, http.MethodPost, "https://api.anthropic.com/v1/messages", headers, payload, &response); err != nil {
		return providerCallResult{}, wrapProviderError("Claude", err)
	}
	var builder strings.Builder
	for _, block := range response.Content {
		if block.Type == "text" {
			builder.WriteString(block.Text)
		}
	}
	return providerCallResult{ResponseText: builder.String()}, nil
}

func callClaudeOAuth(ctx context.Context, _ *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (providerCallResult, error) {
	service, _ := ctx.Value(serviceContextKey{}).(*Service)
	if service == nil || service.oauth == nil {
		return providerCallResult{}, &apiError{StatusCode: http.StatusServiceUnavailable, Message: "Claude OAuth is unavailable"}
	}
	conversation, _ := ctx.Value(conversationContextKey{}).(ConversationDetail)
	prompt := ""
	if len(messages) > 0 {
		prompt = messageTextWithFallback(messages[len(messages)-1])
	}
	return service.oauth.runPrompt(ctx, conversation, model, systemPrompt, prompt)
}

func callGemini(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (providerCallResult, error) {
	endpoint := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s", url.PathEscape(model), url.QueryEscape(config["api_key"]))
	contents := make([]map[string]any, 0, len(messages))
	for _, message := range messages {
		role := message.Role
		if role == "assistant" {
			role = "model"
		}
		parts := []map[string]any{{"text": messageTextWithFallback(message)}}
		if attachment := message.Attachment; attachment != nil && len(attachment.Data) > 0 && supportsNativeDocument("gemini", attachment.MediaType) {
			parts = []map[string]any{}
			if strings.TrimSpace(message.Content) != "" {
				parts = append(parts, map[string]any{"text": message.Content})
			}
			parts = append(parts, map[string]any{"inline_data": map[string]any{"mime_type": attachment.MediaType, "data": base64.StdEncoding.EncodeToString(attachment.Data)}})
		}
		contents = append(contents, map[string]any{
			"role":  role,
			"parts": parts,
		})
	}
	payload := map[string]any{
		"system_instruction": map[string]any{
			"parts": map[string]any{
				"text": systemPrompt,
			},
		},
		"contents": contents,
	}
	var response struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := doJSON(ctx, client, http.MethodPost, endpoint, nil, payload, &response); err != nil {
		return providerCallResult{}, wrapProviderError("Gemini", err)
	}
	if len(response.Candidates) == 0 {
		return providerCallResult{}, &apiError{StatusCode: http.StatusBadGateway, Message: "Gemini returned no candidate"}
	}
	var builder strings.Builder
	for _, part := range response.Candidates[0].Content.Parts {
		builder.WriteString(part.Text)
	}
	return providerCallResult{ResponseText: builder.String()}, nil
}

func callOpenAI(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (providerCallResult, error) {
	payloadMessages := make([]map[string]any, 0, len(messages))
	for _, message := range messages {
		content := any(messageTextWithFallback(message))
		if attachment := message.Attachment; message.Role == "user" && attachment != nil && len(attachment.Data) > 0 && supportsNativeDocument("openai", attachment.MediaType) {
			fileItem := map[string]any{"type": "input_file", "filename": attachment.Filename, "file_data": attachmentDataURL(attachment)}
			if strings.HasPrefix(strings.ToLower(attachment.MediaType), "image/") {
				fileItem = map[string]any{"type": "input_image", "image_url": attachmentDataURL(attachment)}
			}
			items := []map[string]any{fileItem}
			if strings.TrimSpace(message.Content) != "" {
				items = append(items, map[string]any{"type": "input_text", "text": message.Content})
			} else {
				items = append(items, map[string]any{"type": "input_text", "text": "Please analyze the attached file."})
			}
			content = items
		}
		payloadMessages = append(payloadMessages, map[string]any{"role": message.Role, "content": content})
	}
	payload := map[string]any{
		"model":        model,
		"instructions": systemPrompt,
		"input":        payloadMessages,
	}
	headers := map[string]string{
		"Authorization": "Bearer " + config["api_key"],
	}
	var response struct {
		Output []struct {
			Type    string `json:"type"`
			Content []struct {
				Type string `json:"type"`
				Text string `json:"text"`
			} `json:"content"`
		} `json:"output"`
	}
	if err := doJSON(ctx, client, http.MethodPost, "https://api.openai.com/v1/responses", headers, payload, &response); err != nil {
		return providerCallResult{}, wrapProviderError("OpenAI", err)
	}
	var builder strings.Builder
	for _, output := range response.Output {
		for _, content := range output.Content {
			if content.Type == "output_text" {
				builder.WriteString(content.Text)
			}
		}
	}
	if builder.Len() == 0 {
		return providerCallResult{}, &apiError{StatusCode: http.StatusBadGateway, Message: "OpenAI returned no output text"}
	}
	return providerCallResult{ResponseText: builder.String()}, nil
}

func callMistral(ctx context.Context, client *http.Client, model string, systemPrompt string, messages []ConversationMessage, config map[string]string) (providerCallResult, error) {
	payloadMessages := []map[string]string{
		{"role": "system", "content": systemPrompt},
	}
	for _, message := range messages {
		payloadMessages = append(payloadMessages, map[string]string{
			"role":    message.Role,
			"content": messageTextWithFallback(message),
		})
	}
	payload := map[string]any{
		"model":    model,
		"messages": payloadMessages,
	}
	headers := map[string]string{
		"Authorization": "Bearer " + config["api_key"],
	}
	var response struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := doJSON(ctx, client, http.MethodPost, "https://api.mistral.ai/v1/chat/completions", headers, payload, &response); err != nil {
		return providerCallResult{}, wrapProviderError("Mistral", err)
	}
	if len(response.Choices) == 0 {
		return providerCallResult{}, &apiError{StatusCode: http.StatusBadGateway, Message: "Mistral returned no choice"}
	}
	return providerCallResult{ResponseText: response.Choices[0].Message.Content}, nil
}

func doJSON(ctx context.Context, client *http.Client, method string, endpoint string, headers map[string]string, payload any, target any) error {
	request := resty.NewWithClient(client).R().
		SetContext(ctx).
		SetHeader("Content-Type", "application/json").
		ExpectContentType("application/json").
		SetBody(payload).
		SetResult(target)
	for key, value := range headers {
		if strings.TrimSpace(value) != "" {
			request.SetHeader(key, value)
		}
	}
	response, err := request.Execute(method, endpoint)
	if err != nil {
		return &apiError{StatusCode: http.StatusBadGateway, Message: err.Error()}
	}
	responseBody := response.Body()
	if len(responseBody) > 1<<20 {
		responseBody = responseBody[:1<<20]
	}
	if response.StatusCode() >= http.StatusBadRequest {
		message := extractRemoteError(responseBody)
		if message == "" {
			message = strings.TrimSpace(string(responseBody))
		}
		if message == "" {
			message = response.Status()
		}
		return &apiError{StatusCode: http.StatusBadGateway, Message: message}
	}
	return nil
}

func extractRemoteError(body []byte) string {
	var payload struct {
		Error any `json:"error"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		return ""
	}
	switch value := payload.Error.(type) {
	case string:
		return value
	case map[string]any:
		if message, ok := value["message"].(string); ok {
			return message
		}
		if message, ok := value["status"].(string); ok {
			return message
		}
	}
	return ""
}

func wrapProviderError(provider string, err error) error {
	apiErr, ok := err.(*apiError)
	if !ok {
		return err
	}
	message := strings.TrimSpace(apiErr.Message)
	if message == "" {
		message = "request failed"
	}
	return &apiError{
		StatusCode: apiErr.StatusCode,
		Message:    fmt.Sprintf("%s request failed: %s", provider, message),
	}
}
